import com.spire.xls.*;
import com.spire.xls.digital.CertificateAndPrivateKey;

import java.util.Date;

public class addAndRemoveDigitalSignature {

    public static void main(String[] args) throws Exception {
        /**
         * Add digital signature
         */
        //The paths of input and output files
        String addSignatureOut="output/addSignatureOut.xlsx";
        String removeSignatureOut="output/removeSignatureOut.xlsx";
        String input="data/AddDigitalSignature.xlsx";
        //The path of certificate file
        String certificatePath="data/gary.pfx";
        //The password
        String password="e-iceblue";
        //The comment
        String comment="Spire.XLS";
        //Create a workbook
        Workbook workbook=new Workbook();
        //Load the input file
        workbook.loadFromFile(input);
        //Load the certificate file
        CertificateAndPrivateKey cap = new CertificateAndPrivateKey(certificatePath,password);
        //Add digital signature to the workbook
        workbook.addDigitalSignature(cap, comment,new Date());
        //Save the workbook
        workbook.saveToFile(addSignatureOut, ExcelVersion.Version2013);

        /**
         * Remove digital signature
         */
        //Create a workbook
        Workbook workbook2=new Workbook();
        //Load the file which generated by the code above
        workbook2.loadFromFile(addSignatureOut);
        //Remove all digital signatures
        workbook2.removeAllDigitalSignatures();
        //Save the workbook
        workbook2.saveToFile(removeSignatureOut,ExcelVersion.Version2013);

    }
}
